# Generated by Django 5.0.6 on 2024-06-12 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_remove_group_customuser_groups_and_more'),
        ('users', '0002_auto_20240612_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('superuser', 'Superuser'), ('moderator', 'Moderator'), ('employee', 'Employee')], max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission')),
            ],
            options={
                'unique_together': {('user_role', 'permission')},
            },
        ),
    ]
