# Generated by Django 5.0.6 on 2024-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facial_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
